watch_stylesheet: true
watch_config: true
debug: false
komorebi:
  start_command: "komorebic start --whkd"
  stop_command: "komorebic stop --whkd"
  reload_command: "komorebic reload-configuration"

bars:
  Primary-bar:
    enabled: true
    screens: ["*"]
    class_name: "yasb-bar"
    alignment:
      position: "top"
      center: false
    animation:
      enabled: true
      duration: 700
    blur_effect:
      enabled: true
      acrylic: false
      dark_mode: true
      round_corners: true
      round_corners_type: "normal"
      border_color: none
    window_flags:
      always_on_top: false
      windows_app_bar: false
    dimensions:
      width: "100%"
      height: 35
    padding:
      top: 10
      left: 200
      bottom: 10
      right: 200
    widgets:
      left: ["komorebi_workspaces","cava", "wallpapers"]
      center: ["systray", "clock", "power_menu"]
      right: [
          # "systray",
           
          "media",

          # "uspace",
          # "ubattery",
          "divider",

          "weather",
          "divider",
          "volume",
          "divider",
          "memory",
          "divider",
          taskbar,
          "uspace",
        ]
  Secondary-bar:
    enabled: true
    screens: ["5"]
    class_name: "yasb-bar"
    alignment:
      position: "top"
      center: false
    animation:
      enabled: true
      duration: 1000
    blur_effect:
      enabled: true
      acrylic: false
      dark_mode: true
      round_corners: true
      round_corners_type: "normal"
      border_color: none
    window_flags:
      always_on_top: false
      windows_app_bar: false
    dimensions:
      width: "100%"
      height: 35
    padding:
      top: 16
      left: 150
      bottom: 0
      right: 150
    widgets:
      left: ["komorebi_workspaces", "wallpapers"]
      center: ["clock"]
      right: ["systray", "brightness", "divider", "uwifi", "uspace"]
widgets:
  clock:
    type: "yasb.clock.ClockWidget"
    options:
      label: "{%I:%M %b %d}"
      label_alt: "{%I:%M %b %d}"
      timezones: []
      callbacks:
        on_left: "toggle_calendar"
      calendar:
        blur: true
        country_code: "ID"
        show_holidays: true
        show_week_numbers : false
        holiday_color: "#FF6464"
        round_corners: True
        round_corners_type: "normal"
        border_color: None
        alignment: "center"
        direction: "down"
        offset_left: 0
      label_shadow:
        enabled: true
        color: "black"
        radius: 3
        offset: [ 1, 1 ]
  komorebi_workspaces:
    type: "komorebi.workspaces.WorkspaceWidget"
    options:
      label_offline: "\u23fc Offline"
      label_workspace_btn: "\uf444"
      label_workspace_active_btn: "\uf444"
      label_workspace_populated_btn: "\udb82\udfaf"
      label_default_name: "{index}"
      label_zero_index: false
      hide_empty_workspaces: false
      hide_if_offline: true
      animation: true
      container_padding:
        top: 0
        left: 1
        bottom: 0
        right: 0
  komorebi_active_layout:
    type: "komorebi.active_layout.ActiveLayoutWidget"
    options:
      hide_if_offline: true
      label: "{icon}"
      layouts:
        [
          "bsp",
          "columns",
          "rows",
          "grid",
          "vertical_stack",
          "horizontal_stack",
          "ultrawide_vertical_stack",
          "right_main_vertical_stack",
        ]
      layout_icons:
        bsp: "BSP"
        columns: "COLS"
        rows: "ROWS"
        grid: "GRID"
        vertical_stack: "V-STACK"
        horizontal_stack: "H-STACK"
        ultrawide_vertical_stack: "W-STACK"
        right_main_vertical_stack: "RMV-STACK"
        monocle: "MONOCLE"
        maximised: "MAX"
        floating: "FLOATING"
        paused: "PAUSED"
      container_padding:
        top: 0
        left: 8
        bottom: 0
        right: 8
      callbacks:
        on_left: "next_layout"
        on_middle: "toggle_monocle"
        on_right: "prev_layout"
  volume:
    type: "yasb.volume.VolumeWidget"
    options:
      label: "<span>{icon}</span> {level}"
      label_alt: "{volume}"
      volume_icons:
        - "\ueee8" # Icon for muted
        - "\uf026" # Icon for 0-10% volume
        - "\uf027" # Icon for 11-30% volume
        - "\uf027" # Icon for 31-60% volume
        - "\uf028" # Icon for 61-100% volume
      keybindings:
        - keys: "alt+v"
          action: "toggle_menu"

      audio_menu:
        blur: true
        round_corners: True
        round_corners_type: "normal"
        border_color: "System"
        alignment: "center"
        direction: "down"
        distance: 6
        show_apps: true # Whether to show the list of applications with audio sessions
        show_app_labels: false # Whether to show application labels in the audio menu
        show_app_icons: true # Whether to show application icons in the audio menu
        show_apps_expanded: false # Whether application volumes are expanded by default when opening the menu
        app_icons: # Icons for the toggle button to expand/collapse application volumes
          toggle_down: "\uf078" # Icon for btn collapsed state
          toggle_up: "\uf077" # Icon for btn expanded state
      callbacks:
        on_left: "toggle_volume_menu"
        on_right: "toggle_mute"
  divider:
    type: "yasb.custom.CustomWidget"
    options:
      label: "|"
      label_alt: "|"
      class_name: "div-widget"
  battery:
    type: "yasb.battery.BatteryWidget"
    options:
      label: "<span>{icon}</span>{percent}%"
      label_alt: "{icon} {percent}% | time: {time_remaining}"
      charging_options:
        { icon_format: "{charging_icon} {icon}", blink_charging_icon: True }
      status_thresholds:
        { critical: 10, low: 25, medium: 75, high: 95, full: 100 }
      status_icons:
        {
          icon_charging: '\uf0e7',
          icon_critical: '\uf244',
          icon_low: '\uf243',
          icon_medium: '\uf242',
          icon_high: '\uf241',
          icon_full: '\uf240',
        }
      animation: { "enabled": True, "type": "fadeInOut", "duration": 200 }
      callbacks:
        {
          on_left: "toggle_label",
          on_middle: "do_nothing",
          on_right: "do_nothing",
        }
      container_padding: { "top": 0, "left": 0, "bottom": 0, "right": 0 }
  brightness:
    type: "yasb.brightness.BrightnessWidget"
    options:
      label: "<span>{icon}</span> {percent}%"
      label_alt: "Brightness {percent}%"
      tooltip: true
      hide_unsupported: true
      brightness_toggle_level: [0, 50, 100]
      auto_light: false
      auto_light_icon: "\udb80\udce1"
      auto_light_night_level: 35
      auto_light_night_start_time: "19:00"
      auto_light_night_end_time: "06:45"
      auto_light_day_level: 75
      brightness_icons: [
          "\uf522", # Icon for 0-25% brightness
          "\uf522", # Icon for 26-50% brightness
          "\uf522", # Icon for 51-75% brightness
          "\uf522", # Icon for 76-100% brightness
        ]
      brightness_menu:
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "System"
        alignment: "right"
        direction: "down"
        distance: 6
      callbacks:
        on_left: "toggle_label"
      container_padding:
        top: 0
        left: 8
        bottom: 0
        right: 8
  memory:
    type: "yasb.memory.MemoryWidget"
    options:
      label: "<span>{virtual_mem_percent}%</span>"
      label_alt: "<span>MEM<span> VIRT: {virtual_mem_percent}% SWAP: {swap_mem_percent}%"
      update_interval: 5000
      callbacks:
          on_left: "toggle_label"
          on_middle: "do_nothing"
          on_right: "do_nothing"
      memory_thresholds:
          low: 25
          medium: 50
          high: 90
        # histogram_icons:
        #   - "\u2581" # 0%
        #   - "\u2581" # 10%
        #   - "\u2582" # 20%
        #   - "\u2583" # 30%
        #   - "\u2584" # 40%
        #   - "\u2585" # 50%
        #   - "\u2586" # 60%
        #   - "\u2587" # 70%
        #   - "\u2588" # 80%+
        # label_shadow:
        #   enabled: true
        #   color: "black"
        #   radius: 3
        #   offset: [ 1, 1 ]
      progress_bar:
          enabled: true
          thickness: 3
          color: "#9ba2a7" # Single color # color: ["#57948a","#ff0000"] # Gradient colors
          background_color: "#2C2C2C" 
  network:
    type: "yasb.wifi.WifiWidget"
    options:
      label: "<span>{wifi_icon}</span> {wifi_name}"
      label_alt: "{wifi_name} {wifi_strength}%"
      update_interval: 5000
      callbacks:
        on_left: "exec cmd.exe /c start ms-settings:network"
        on_middle: "do_nothing"
        on_right: "toggle_label"
      wifi_icons: [
          "\udb82\udd2e", # Icon for 0% strength
          "\udb82\udd1f", # Icon for 1-20% strength
          "\udb82\udd22", # Icon for 21-40% strength
          "\udb82\udd25", # Icon for 41-80% strength
          "\udb82\udd28", # Icon for 81-100% strength
        ]
  systray:
    type: "yasb.systray.SystrayWidget"
    options:
      class_name: "systray"
      label_collapsed: ""
      label_expanded: ""
      label_position: "right"
      icon_size: 14
      pin_click_modifier: "alt"
      show_unpinned: false
      show_unpinned_button: true
      show_battery: false
      show_volume: false
      show_network: false
      show_in_popup: true
      icons_per_row: 4
      popup:
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: None
        alignment: "center"
        direction: "down"
        offset_top: 6
        offset_left: 0
  wallpapers:
    type: "yasb.wallpapers.WallpapersWidget"
    options:
      label: ""
      image_path: "C:\\Users\\khabsi\\Pictures\\wallpapers"
      change_automatically: false
      update_interval: 60
      gallery:
        enabled: true 
        blur: true
        image_width: 350
        image_per_page: 5
        show_buttons: false
        orientation: "landscape"
        image_spacing: 15
        lazy_load: true
        lazy_load_delay: 80
        lazy_load_fadein: 400
        image_corner_radius: 20
        enable_cache: false
     
  uwifi:
    type: "yasb.custom.CustomWidget"
    options:
      label: " pixel "
      label_alt: " pixel "
      class_name: "uwifi-widget"
  ubattery:
    type: "yasb.custom.CustomWidget"
    options:
      label: "  100%"
      label_alt: "  100%"
      class_name: "ubattery-widget"
  uspace:
    type: "yasb.custom.CustomWidget"
    options:
      label: "ㅤ‎"
      label_alt: "‎ㅤ"
      class_name: "uspace-widget"
  power_menu:
    type: "yasb.power_menu.PowerMenuWidget"
    options:
      label: ""
      uptime: true
      show_user: true
      blur: false
      blur_background: true
      animation_duration: 120 # Milliseconds
      button_row: 3 # Number of buttons in a row, min 1 max 6
      profile_image_size: 80 # Avatar size in pixels
      buttons:
        restart: ["\uead2", "Restart"]
        shutdown: ["\uf011", "Shut Down"]
        signout: ["\udb80\udf43", "Sign out"]
        hibernate: ["\uf28e", "Hibernate"]
        lock: ["\uea75", "Lock"]
        cancel: ["\udb81\udf3a", "Cancel"]
      label_shadow:
        enabled: false
        color: "black"
        radius: 3
        offset: [ 1, 1 ]
  

  cava:
    type: "yasb.cava.CavaWidget"
    options:
      bar_height: 17
      callbacks:
        on_left: "reload_cava"
      gradient: 0
      edge_fade: 15
      framerate: 60
      mono_option: "average"
      channels: "stereo"
      reverse: 0
      noise_reduction: 30
      foreground: "#9ba2a7"
      bars_number: 10
      bar_spacing: 1
      bar_width: 4
      bar_type: "bars_mirrored"
      sleep_timer: 2
      hide_empty: false
      container_padding:
        top: 1
        right: 8
        bottom: 0
        left: 8
  taskbar:
    type: "yasb.taskbar.TaskbarWidget"
    options:
      icon_size: 16
      tooltip: true
      show_only_visible: false
      strict_filtering: true
      monitor_exclusive: false
      animation:
        enabled: true
      preview:
        enabled: true
        width: 240
        delay: 400
        padding: 8
        margin: 8
      ignore_apps:
        processes: []
        titles: []
        classes: []
  win_button:
    type: "yasb.custom.CustomWidget"
    options:
      label: "\ue62a"
      label_alt: "\ue62a"
      class_name: "win-button-widget"
      callbacks:
        on_left: "exec start_menu"
  weather:
    type: "yasb.weather.WeatherWidget"
    options:
      label: "<span>{icon}</span> {temp}"
      label_alt: "{location}: Min {min_temp}, Max {max_temp}, Humidity {humidity}"
      api_key: '200b851ca19a4f99abd145812250105' # Get your free API key from https://www.weatherapi.com/
      update_interval: 600 # Update interval in seconds, Min 600 seconds
      hide_decimal: true
      units: "metric" # Can be 'metric' or 'imperial'
      location: "IND Jepara 59464" # You can use "USA Los Angeles 90006" {COUNTRY CITY ZIP_CODE}, or just city.
      callbacks:
        on_left: "toggle_card"
        on_middle: "do_nothing"
        on_right: "toggle_label"
      icons: 
        sunnyDay: "\ue30d"
        clearNight: "\ue32b"
        cloudyDay: "\udb81\udd99"
        cloudyNight: "\ue311"
        rainyDay: "\udb81\ude7e"
        rainyNight: "\udb81\ude7e"
        snowyDay: "\udb81\udd98"
        snowyNight: "\udb81\udd98"
        blizzardDay: "\uebaa"
        blizzardNight: "\uebaa"
        foggyDay: "\ue303"
        foggyNight: "\ue346"
        thunderstormDay: "\ue30f"
        thunderstormNight: "\ue338"
        default: "\uebaa"
      weather_card: 
        blur: true
        round_corners: True
        round_corners_type: "normal"
        border_color: "System"
        alignment: "center"
        direction: "down"
        distance: 6
        icon_size: 64
        show_hourly_forecast: true # Set to False to disable hourly forecast
        time_format: "24h" # can be 12h or 24h
        hourly_point_spacing: 76
        hourly_icon_size: 32 # better to set 16, 32 or 64 for better quality
        icon_smoothing: true # should be true for smoother icon or false for sharper icon if using 16, 32 or 64 for hourly_icon_size
        temp_line_width: 2 # can be 0 to hide the temperature line
        current_line_color: "#8EAEE8"
        current_line_width: 1 # can be 0 to hide the current hour line
        current_line_style: "dot"
        hourly_gradient:
          enabled: false
          top_color: "#8EAEE8"
          bottom_color: "#2A3E68"
        hourly_forecast_buttons: # Optional hourly forecast data type toggle buttons, default disabled
          enabled: false # Set to false to hide the buttons
          default_view: "temperature" # Default view when opening the weather card. Options: "temperature", "rain", "snow"
          temperature_icon: "\udb81\udd99"
          rain_icon: "\udb81\udd96"
          snow_icon: "\udb81\udd98"
        weather_animation:
          enabled: false
          snow_overrides_rain: true
          temp_line_animation_style: both # can be "rain", "snow", "both", or "none"
          rain_effect_intensity: 1.0 # 0.01 - 10.0
          snow_effect_intensity: 1.0 # 0.01 - 10.0
          scale_with_chance: true
          enable_debug: false
      label_shadow:
        enabled: true
        color: "black"
        radius: 3
        offset: [ 1, 1 ]
    
  media:
    type: "yasb.media.MediaWidget"
    options:
      label: "{title}-{artist}"
      label_alt: "{title}"
      hide_empty: true
      callbacks:
        on_left: "toggle_media_menu"
        on_middle: "do_nothing"
        on_right: "do_nothing"
      max_field_size:
        label: 8
        label_alt: 30
      show_thumbnail: false
      controls_only: false
      controls_left: true
      controls_hide: false
      thumbnail_alpha: 80
      thumbnail_padding: 8
      thumbnail_corner_radius: 16
      icons:
        prev_track: "\udb81\udcae"
        next_track: "\udb81\udcad"
        play: "\udb81\udc0a"
        pause: "\udb80\udfe4"
      media_menu:
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "system"
        alignment: "center"
        direction: "down"
        offset_top: 6
        offset_left: 0
        thumbnail_corner_radius: 16
        show_volume_slider: true
        thumbnail_size: 120
        max_title_size: 60
        max_artist_size: 20
        show_source: true
      media_menu_icons:
        play: "\ue768"
        pause: "\ue769"
        prev_track: "\ue892"
        next_track: "\ue893"
       
      scrolling_label:
        enabled: true
        update_interval_ms: 33
        style: "left"  # can be "left", "right", "bounce", "bounce-ease"
        separator: " | "
        label_padding: 1
        # Easing curve params: https://www.desmos.com/calculator/j7eamemxzi
        ease_slope: 20
        ease_pos: 0.8
        ease_min: 0.5
      label_shadow:
        enabled: true
        color: "black"
        radius: 3
        offset: [ 1, 1 ]

  pomodoro:
    type: "yasb.pomodoro.PomodoroWidget"
    options:
      label: "<span>{icon}</span> {remaining}"
      label_alt: "<span>{icon}</span> {session}/{total_sessions} - {status}"
      work_duration: 410
      break_duration: 5
      long_break_duration: 15
      long_break_interval: 4
      auto_start_breaks: true
      auto_start_work: true
      sound_notification: true
      show_notification: true
      hide_on_break: false
      session_target: 8
      icons:
        work: "\uf252"
        break: "\uf253"
        paused: "\uf254"
      menu:
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "System"
        alignment: "center"
        direction: "down"
        offset_top: 6
        offset_left: 0
        circle_background_color: "#09ffffff"
        circle_work_progress_color: "#88c0d0"
        circle_break_progress_color: "#a3be8c"
        circle_thickness: 8
        circle_size: 160
      callbacks:
        on_left: "toggle_menu"
        on_middle: "reset_timer"
        on_right: "toggle_label"
      label_shadow:
        enabled: true
        color: "black"
        radius: 3
        offset: [ 1, 1 ]